-- Create subtask_presets table for storing reusable subtask templates
CREATE TABLE public.subtask_presets (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL,
  subtask_names TEXT[] NOT NULL DEFAULT '{}',
  user_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.subtask_presets ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own subtask presets" 
ON public.subtask_presets 
FOR SELECT 
USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own subtask presets" 
ON public.subtask_presets 
FOR INSERT 
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own subtask presets" 
ON public.subtask_presets 
FOR UPDATE 
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own subtask presets" 
ON public.subtask_presets 
FOR DELETE 
USING (auth.uid() = user_id);

-- Create trigger for updating updated_at
CREATE TRIGGER update_subtask_presets_updated_at
BEFORE UPDATE ON public.subtask_presets
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();