
CREATE TABLE public.progress_pulse_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pulse_task_id BIGINT NOT NULL,
  item_name TEXT NOT NULL,
  item_type TEXT NOT NULL DEFAULT 'subtask',
  is_completed BOOLEAN NOT NULL DEFAULT false,
  user_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.progress_pulse_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own pulse items"
  ON public.progress_pulse_items FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own pulse items"
  ON public.progress_pulse_items FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can update their own pulse items"
  ON public.progress_pulse_items FOR UPDATE USING (auth.uid() = user_id);
CREATE POLICY "Users can delete their own pulse items"
  ON public.progress_pulse_items FOR DELETE USING (auth.uid() = user_id);
