// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjngziesjqltethpvogp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqbmd6aWVzanFsdGV0aHB2b2dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTI2ODgsImV4cCI6MjA1NDc4ODY4OH0.t25gyPJO_FxCm6kOl-F1-AL8mk96gt5ty0oa9TeJydY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);